### ISSUE TITLE
Security Example Documentation 

### ISSUE THREAD

**Issue by bluengreen** [kogosoftwarellc/fetch-openapi#7]
Any way to get a better usage examples? Specifically the options object when creating a new instance, and the security examples. Its not really clear what the security handler is suppose to do. Our API is using OAuth2 with a password grant type flow. Not really sure what a handler would look like for use with this. Examples would be immensely useful. 

Thanks

**Comment by jsdevel** [comment]
Please re-open this here https://github.com/kogosoftwarellc/open-api
